title   Velaris
linux   /arch/boot/x86_64/vmlinuz-linux-cachyos
initrd  /arch/boot/x86_64/initramfs-linux-cachyos.img
options archisobasedir=arch archisolabel=%ARCHISO_LABEL% quiet splash loglevel=3 zswap.enabled=0
