---
dontChroot: false
timeout: 30
"packagechooser_kernel":
  bore-lto: "/usr/lib/velaris/record-selection kernel bore-lto"
  cachyos: "/usr/lib/velaris/record-selection kernel cachyos"
  lts: "/usr/lib/velaris/record-selection kernel lts"
  arch: "/usr/lib/velaris/record-selection kernel arch"
  "*": "/bin/false invalid-kernel-selection"
"packagechooser_graphics":
  nvidia-open: "/usr/lib/velaris/record-selection graphics nvidia-open"
  nouveau: "/usr/lib/velaris/record-selection graphics nouveau"
  amd: "/usr/lib/velaris/record-selection graphics amd"
  intel: "/usr/lib/velaris/record-selection graphics intel"
  virtual: "/usr/lib/velaris/record-selection graphics virtual"
  universal: "/usr/lib/velaris/record-selection graphics universal"
  "*": "/bin/false invalid-graphics-selection"
"packagechooser_profile":
  balanced: "/usr/lib/velaris/record-selection profile balanced"
  performance: "/usr/lib/velaris/record-selection profile performance"
  powersave: "/usr/lib/velaris/record-selection profile powersave"
  "*": "/bin/false invalid-profile-selection"
