---
dontChroot: false
timeout: 600
verbose: true
script:
  - "install -d -m 0755 /var/lib/velaris"
  - "touch /var/lib/velaris/firstboot-plymouth"
  - command: "plymouth-set-default-theme -R velaris-firstboot"
    timeout: 600
    verbose: true
i18n:
  name: "Preparing the first boot"
