---
dontChroot: false
timeout: 1200
verbose: true
script:
  - command: "/usr/lib/velaris/apply-selections"
    timeout: 1200
    verbose: true
i18n:
  name: "Applying hardware and performance choices"
