---
modules-search: [ local, /usr/lib/calamares/modules ]

instances:
  # Os nomes *_velaris.conf são intencionais: não colidem com os arquivos
  # pertencentes ao pacote cachyos-calamares.
  - id: velaris
    module: partition
    config: partition_velaris.conf
  - id: velaris
    module: mount
    config: mount_velaris.conf
  - id: velaris
    module: unpackfs
    config: unpackfs_velaris.conf
  - id: velaris
    module: users
    config: users_velaris.conf
  - id: velaris
    module: displaymanager
    config: displaymanager_velaris.conf
  - id: velaris
    module: grubcfg
    config: grubcfg_velaris.conf
  - id: velaris
    module: bootloader
    config: bootloader_velaris.conf
  - id: velaris
    module: initcpiocfg
    config: initcpiocfg_velaris.conf
  - id: velaris
    module: services-systemd
    config: services-systemd_velaris.conf
  - id: velaris
    module: removeuser
    config: removeuser_velaris.conf
  - id: cleanup
    module: packages
    config: packages_cleanup.conf
  - id: firstboot
    module: shellprocess
    config: shellprocess_firstboot.conf
  - id: keyring
    module: shellprocess
    config: shellprocess_keyring.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition@velaris
    - users@velaris
    - summary
  - exec:
    - partition@velaris
    - mount@velaris
    - unpackfs@velaris
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - luksbootkeyfile
    - luksopenswaphookcfg
    - initcpiocfg@velaris
    - initcpio
    - removeuser@velaris
    - users@velaris
    - networkcfg
    - displaymanager@velaris
    - hwclock
    - shellprocess@keyring
    - grubcfg@velaris
    - bootloader@velaris
    - services-systemd@velaris
    - shellprocess@firstboot
    - packages@cleanup
    - umount
  - show:
    - finished

branding: velaris
prompt-install: false
dont-chroot: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
