# Velaris — pacman.conf (runtime)

[options]
HoldPkg      = pacman glibc
Architecture = x86_64
Color
CheckSpace
ParallelDownloads = 5
ILoveCandy
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

# CachyOS — SigLevel Optional evita erro de chave PGP
[cachyos]
SigLevel = Optional TrustAll
Server = https://mirror.cachyos.org/repo/x86_64/$repo
Server = https://repo.cachyos.org/$repo/x86_64

# CachyOS v3 — binários otimizados pra CPUs modernas (x86_64_v3)
# Habilite se seu processador for moderno (2013+)
# [cachyos-v3]
# SigLevel = Optional TrustAll
# Server = https://mirror.cachyos.org/repo/x86_64_v3/$repo
